version: "2"

networks:
  olympus_net:
    driver: bridge

services:

  infra_router:
    container_name: olympus_infra--config-server
    image: macielbombonato/olympus_infra--config-server:latest
    #restart: always
    ports:
      - "8888:8888"
    environment:
      - ENVIRONMENT=dev
      - LOGGIN_LEVEL=debug
      - DEBUG_REQUEST=true
      - GIT_CONFIG_REPO=https://github.com/macielbombonato/olympus/tree/master/infra/configuration-files

