server:
  port: 8888

management:
  context_path: /admin

info:
  component: Config Server

spring:
  application:
    name: olympus_infra--config-server
  profiles: cloud
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/spring-cloud-samples/config-repo
          uri: https://github.com/macielbombonato/olympus/tree/master/infra/configuration-files
          repos:
            #- patterns: multi-repo-demo-*
            - uri: https://github.com/macielbombonato/olympus/tree/master/infra/configuration-files
