version: "2"

networks:
  olympus_net:
    driver: bridge

services:

  infra_router:
    container_name: olympus_infra--eureka
    image: macielbombonato/olympus_infra--eureka:latest
    #restart: always
    ports:
      - "8761:8761"
    environment:
      - ENVIRONMENT=dev
      - CONFIG_SERVER_URL=http://localhost:8888
      - LOGGIN_LEVEL=debug
      - DEBUG_REQUEST=true

