version: "2"

networks:
  olympus_net:
    driver: bridge

services:

  infra_router:
    container_name: olympus_infra--zuul
    image: macielbombonato/olympus_infra--zuul:latest
    #restart: always
    ports:
      - "80:9000"
    environment:
      - ENVIRONMENT=hml
      - CONFIG_SERVER_URL=http://localhost
      - LOGGIN_LEVEL=debug
      - DEBUG_REQUEST=true

